// <auto-generated />
namespace DIVULGA_SERVICOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Pincipal10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pincipal10));
        
        string IMigrationMetadata.Id
        {
            get { return "201610042143127_Pincipal10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
