// <auto-generated />
namespace DIVULGA_SERVICOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Principal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Principal));
        
        string IMigrationMetadata.Id
        {
            get { return "201702261906520_Principal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
